import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import {notFound} from 'next/navigation';
import {routing} from '@/i18n/routing';

import { NextIntlClientProvider, hasLocale } from 'next-intl';
import Header from "@/components/Header";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function LocaleLayout({ children, params }: Props) {
  // Ensure that the incoming `locale` is valid
  const {locale} = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html 
      lang={locale} 
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body>
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem={true}>
        <NextIntlClientProvider locale={locale}>
          <Header />
          <main>{children}</main>
        </NextIntlClientProvider>
      </ThemeProvider>
      </body>
    </html>
  );
}

// todo - https://next-intl.dev/docs/routing/setup#static-rendering
export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "pl" }, { locale: "ru" }];
}
